services:
  - type: web
    name: graa-document-extractor
    env: node
    plan: free
    rootDir: pdf-extractor-service
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: PORT
        value: 10000
      - key: HOST
        value: 0.0.0.0
      - key: NODE_ENV
        value: production
