services:
  - type: web
    name: graa-pdf-extractor
    env: python
    region: oregon
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    autoDeploy: true
    healthCheckPath: /health
